### ISSUE TITLE
Image of size 1920x1080 needed for home.html

### ISSUE THREAD

**Issue by P0intMaN** [P0intMaN/zbunker-website#10]
To create a gallery view, I need an image of **nmap** and **git essentials** in a `1920x1080` format. The style of images should be **"fade-from-one side"**. 

I will use these images in our **Popular Basic Bundles** section.

**Comment by CYBERDEVILZ** [comment]
I hope I have already addressed this issue in #82

**Comment by P0intMaN** [comment]
Alright, my bad. Very well, I will close this issue then.
