### ISSUE TITLE
Migrate to PostgreSQL

### ISSUE THREAD

**Issue by ashutoshkrris** [P0intMaN/zbunker-website#106]
I can work on this issue
The database will be migrated from SQLite3 to PostgreSQL
Also, I'll use Flask-Migrate to maintain the database migrations easily in the future

- [x] Hacktoberfest 2021

**Comment by P0intMaN** [comment]
Hi again @ashutoshkrris ,

Sounds great! In fact, I have blurred vision about this migration part and was looking for someone who could orchestrate this. You may go ahead with this if you'd like. I highly appreciate your commitment towards our project.
