### ISSUE TITLE
[Bug] Raw Passwords Getting Stored

### ISSUE THREAD

**Issue by ashutoshkrris** [P0intMaN/zbunker-website#113]
As of now, whenever a user registers, the raw password is being stored in the database.
Ideally, raw passwords should be hashed and then stored in the database.

I can work on this issue. Using Werkzeug we can hash passwords, and during login, we can match it with the one stored in the database.

- [x] Hacktoberfest 2021

**Comment by P0intMaN** [comment]
Yes, that's an issue being considered under the security section. We talked about using flask-bcrypt to do this. But still now, no one has taken up this issue. So I guess, I'd have you take this up then.

**Comment by P0intMaN** [comment]
One more thing @ashutoshkrris , Would you mind if we take you as one of our core developers? You have been demonstrating good amount of interests in this project. Would love to have you around.

**Comment by P0intMaN** [comment]
Yea you may go ahead with this.

**Comment by ashutoshkrris** [comment]
Oh my bad!
Didn't see it
