### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by P0intMaN** [P0intMaN/zbunker-website#80]
Add a license file for zbunker-website

**Comment by rockingrohit9639** [comment]
> Add a license file for zbunker-website

I would like to work on this issue.

**Comment by P0intMaN** [comment]
Hi @rockingrohit9639, 
Thank you very much for your interest in this project. This issue is resolved. However, feel free to checkout other issues. We will be more than happy to review it!

Happy Hacktoberfest.
