### ISSUE TITLE
Fix Layout of Basic plan bundles (homepage)

### ISSUE THREAD

**Issue by P0intMaN** [P0intMaN/zbunker-website#83]
Currently, the **Basic Plan Bundles** section has many cards. Two of such cards are small (intentionally). Both of them are on the right hand side. Shift one of them towards left hand side and below the **C Programming** card

**Comment by shashank1503-cipher** [comment]
Hey i would like to work on it

**Comment by arayush841** [comment]
Hey @P0intMaN , I would like to work on this issue.

**Comment by P0intMaN** [comment]
Great! Thanks for your interests. Both of you can start working on the issue. Would love to review them!

Happy hacktoberfest

**Comment by P0intMaN** [comment]
Ok, I think I should brief you more on this:

So essentially, I'd want to interchange the positioning of Linux card with that of the Nmap card. Would need to know the basic HTML layout to do so. Using bootstrap as the front end framework

**Comment by P0intMaN** [comment]
Thanks @arayush841 , I think its safe to close this issue now.
