### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by P0intMaN** [P0intMaN/zbunker-website#90]
Currently, zbunker-website doesn't have a pull request template. Would be a great issue for the beginners and first time contributors.

**Comment by TusharSharmaIN** [comment]
hey please assign this to me.

**Comment by P0intMaN** [comment]
Hey @TusharSharmaIN , Thanks for your interest. Sure thing. I am assigning you this task.

**Comment by P0intMaN** [comment]
The issue has been addressed in #95
