### ISSUE TITLE
Security issue: Flask app is running in debug mode

### ISSUE THREAD

**Issue by P0intMaN** [P0intMaN/zbunker-website#91]
I assume that **turning on flask debugger** might cause problems as it paves way for attackers to **run arbitrary code** through the debugger. Hence, **turning off the debugger** might prove to be the solution to this. But then, all the folks forking this repo would want to **turn it back on when they would like to experiment with the website**.

I think this is a good issue for beginners who would want to try their hand and get their first PR accepted.

**Comment by JanviRaina** [comment]
So we want to turn off the debug? You can assign this to me.

**Comment by P0intMaN** [comment]
Hey @JanviRaina ,

Thanks for your interest in this project. Yes you are correct. Just turn off the debug. That will do.
